# Generated by Django 2.2.24 on 2021-07-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='suthor',
            new_name='author',
        ),
    ]
